### ISSUE TITLE
surf-server doesn't seem to find its home/views correctly

### ISSUE THREAD

**Issue by riverar** [surf-build/surf#36]
Windows Server Core 2016

I called surf-server from C:\Build and it's trying to load \views from working directory instead of, perhaps, its node_modules\surf-build home.

Repro:
1. Create C:\Build
2. `npm install surf-build`
3. `set path=%path%;.\node_modules\.bin`
4. `surf-server [args]`
5. Hit http://localhost:3000 and notice dump below

Stack:
```
Error: Failed to lookup view "status" in views directory "C:\Build\views"
   at EventEmitter.render (C:\Build\node_modules\express\lib\application.js:579:17)
   at ServerResponse.render (C:\Build\node_modules\express\lib\response.js:960:7)
   at C:\Build\node_modules\surf-build\lib\ref-server-api.js:56:9
   at Layer.handle [as handle_request] (C:\Build\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\Build\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\Build\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\Build\node_modules\express\lib\router\layer.js:95:5)
   at C:\Build\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\Build\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Build\node_modules\express\lib\router\index.js:271:10)
   at expressInit (C:\Build\node_modules\express\lib\middleware\init.js:33:5)
   at Layer.handle [as handle_request] (C:\Build\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Build\node_modules\express\lib\router\index.js:312:13)
   at C:\Build\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (C:\Build\node_modules\express\lib\router\index.js:330:12)
   at next (C:\Build\node_modules\express\lib\router\index.js:271:10)
```

**Comment by paulcbetts** [comment]
Ya, everything about that status page is broken, just ignore it for now

**Comment by riverar** [comment]
I presume this means surf-client/surf-server functionality doesn't work at this time?

**Comment by paulcbetts** [comment]
That part works, just not the status page. You also probably don't actually need `surf-surver` right now because we're now way more efficient on GitHub API calls
