### ISSUE TITLE
Error: no

### ISSUE THREAD

**Issue by riverar** [surf-build/surf#37]
surf-client debug output

```
Command to run not specified, defaulting to 'surf-build'
500 - {"error":"no"}
  surf:run-on-every-ref StatusCodeError: 500 - {"error":"no"}
    at new StatusCodeError (C:\Build\node_modules\request-promise\lib\errors.js:32:15)
    at Request.RP$callback [as _callback] (C:\Build\node_modules\request-promise\lib\rp.js:77:29)
    at Request.self.callback (C:\Build\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Build\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Build\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +0ms
```

surf-server debug output

```
express:router dispatching GET /info/riverar/HoloToolkit-Unity +2s
express:router query  : /info/riverar/HoloToolkit-Unity +0ms
express:router expressInit  : /info/riverar/HoloToolkit-Unity +0ms
surf:ref-server-api no +0ms
surf:ref-server-api Error: no
  at _callee$ (C:\Build\node_modules\surf-build\lib\ref-server-api.js:95:31)
  at tryCatch (C:\Build\node_modules\regenerator-runtime\runtime.js:62:40)
  at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Build\node_modules\regenerator-runtime\runtime.js:336:22)
  at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Build\node_modules\regenerator-runtime\runtime.js:95:21)
  at tryCatch (C:\Build\node_modules\regenerator-runtime\runtime.js:62:40)
  at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Build\node_modules\regenerator-runtime\runtime.js:278:24)
  at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Build\node_modules\regenerator-runtime\runtime.js:95:21)
  at step (C:\Build\node_modules\surf-build\lib\ref-server-api.js:34:191)
  at C:\Build\node_modules\surf-build\lib\ref-server-api.js:34:451
  at new Promise (C:\Build\node_modules\core-js\modules\es6.promise.js:191:7)
  at C:\Build\node_modules\surf-build\lib\ref-server-api.js:34:99
  at C:\Build\node_modules\surf-build\lib\ref-server-api.js:147:18
  at Layer.handle [as handle_request] (C:\Build\node_modules\express\lib\router\layer.js:95:5)
  at next (C:\Build\node_modules\express\lib\router\route.js:131:13)
  at Route.dispatch (C:\Build\node_modules\express\lib\router\route.js:112:3)
  at Layer.handle [as handle_request] (C:\Build\node_modules\express\lib\router\layer.js:95:5) +21ms
```

**Comment by paulcbetts** [comment]
This means that you tried to fetch info for a repo that you didn't set up ahead-of-time in the `surf-server` parameters
